#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail
BUILD_COMMAND="gradle $@ --no-daemon --parallel --console plain"
CONTAINER_PREFIX=octopus-${BRANCH_NAME:=unknown}
cat > ${PWD}/docker-compose.yml <<EOF
version: '3'
services:
  gradle:
    image: gradle:4.8
    container_name: ${CONTAINER_PREFIX}.gradle
    user: root
    volumes:
      - ${PWD}:/home/gradle/project
    working_dir: /home/gradle/project
    command: ${BUILD_COMMAND}
EOF

docker-compose --no-ansi up --exit-code-from gradle --remove-orphans && rm ${PWD}/docker-compose.yml