pipeline {
  options { disableConcurrentBuilds() }
  agent any
  stages {
    stage("Assemble") {
      steps {
        sh "chmod +x gradlew"
        sh "./gradlew clean"
        sh "./gradlew assemble"
      }
    }
    stage("Unit Test") {
      steps {
        sh "./gradlew clean check"
      }
    }
    stage("Build/Upload") {
      when { branch 'dev' }
      steps {
        sh "./gradlew dockerPush -Dgit.commit='${GIT_COMMIT.substring(0,7)}'"
      }
    }
  }
}