pipeline {
  options { disableConcurrentBuilds() }
  agent any
  stages {
    stage("Assemble") {
      steps {
        sh "chmod +x gradlew"
        sh "./gradlew clean"
        sh "./gradlew assemble"
      }
    }
    stage("Unit Test") {
      steps {
        sh "./gradlew clean check"
      }
    }
  }
}